apiVersion: v1
kind: Pod
metadata:
  name: ar-sync
  labels:
    tier: api
spec:
  volumes:
    - name: ar
      persistentVolumeClaim:
        claimName: ar
  containers:
  - name: schema
    imagePullPolicy: Always
    image: argovis/ar-sync:dev
    command: ['sleep', '1000000']
    #command: ['bash', 'loaddata.sh']
    volumeMounts:
      - mountPath: "/tmp"
        name: ar
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 1Gi
        cpu: 1000m
  restartPolicy: Never