[package]
name = "munge_ars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.1.1"
tokio = "1"
tokio-stream = "0.1.13"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
