apiVersion: v1
kind: Pod
metadata:
  name: ar-munge-roundtrip
  labels:
    tier: api
spec:
  containers:
  - name: ar-munge-roundtrip
    imagePullPolicy: Always
    image: argovis/ar-sync:munge-roundtrip
    command: ['python', '-u', 'roundtrip.py']
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 1000Mi
        cpu: 500m
  restartPolicy: Never
