apiVersion: v1
kind: Pod
metadata:
  name: ar-munge
  labels:
    tier: api
spec:
  containers:
  - name: ar-munge
    imagePullPolicy: Always
    image: argovis/ar-sync:munge
    command: ['cargo', 'run']
    env:
    - name: MONGODB_URI
      value: "mongodb://database/argo"
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 1000Mi
        cpu: 500m
  restartPolicy: Never
